PIDI/Controllers/Admin/PromotionController.cs
using MongoDB.Driver;
using PIDI.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PIDI.Models.Admin;
using MongoDB.Bson;
using PIDI.Models;
using System.Web.Helpers;

namespace PIDI.Controllers.Admin
{
    public class PromotionController : Controller
    {

        private MongoDBContext dBContext;
        private IMongoCollection<PromotionModel> promotionCollection;

        public static PromotionModel promotionModel;
        private static PromotionController _instance;

        public static PromotionController Instance
        {
            get
            {
                return GetInstace();
            }
            set { }
        }
        private static PromotionController GetInstace()
        {
            if (_instance == null)
            {
                _instance = new PromotionController();
                return _instance;
            }
            else
                return _instance;
        }

        public PromotionController()
        {
            dBContext = new MongoDBContext();
            promotionCollection = dBContext.database.GetCollection<PromotionModel>("promotions");
        }

        // GET: Promotion
        public ActionResult Index()
        {
            List<PromotionModel> promotions = promotionCollection.AsQueryable<PromotionModel>().ToList();
            return View(promotions);
        }

        public ActionResult EditPromotion(string id)
        {
            var productID = new ObjectId(id);
            var promotion = promotionCollection.AsQueryable<PromotionModel>().SingleOrDefault(x => x.id == productID);
            return View(promotion);
        }

        [HttpPost]
        public ActionResult EditPromotion(string id ,PromotionModel promotion, string productsString)
        {
            string[] productsId = productsString.Split(',');
            List<ProductModel> products = new List<ProductModel>();
            for (int i = 0; i < productsId.Length; i++)
            {
                var target = productsId[i];
                var product = ProductController.Instance.GetProduct(target);
                products.Add(product);
            }
            promotion.products = products;

            var filter = Builders<PromotionModel>.Filter.Eq("_id", ObjectId.Parse(id));
            var update = Builders<PromotionModel>.Update
                .Set("PromotionName", promotion.PromotionName)
                .Set("DiscountAmount", promotion.discountAmount)
                .Set("Products", products)
                .Set("InitDate", promotion.InitDate)
                .Set("EndDate", promotion.EndDate);

            var result = promotionCollection.UpdateOne(filter, update);
            return null;
        }

        public ActionResult PromotionDetails(string id)
        {
            var productID = new ObjectId(id);
            var promotion = promotionCollection.AsQueryable<PromotionModel>().SingleOrDefault(x => x.id == productID);
            return View(promotion);
        }

        public ActionResult CreatePromotion()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePromotion(PromotionModel promotion , string productsString)
        {
            try
            {
                string[] productsId = productsString.Split(',');
                List<ProductModel> products = new List<ProductModel>();
                for (int i = 0; i < productsId.Length; i++)
                {
                    var target = productsId[i];
                    var product = ProductController.Instance.GetProduct(target);
                    products.Add(product);
                }
                promotion.products = products;

                promotionCollection.InsertOne(promotion);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult DeletePromotion(string id)
        {
            var promotionID = new ObjectId(id);
            var promotion = promotionCollection.AsQueryable<PromotionModel>().SingleOrDefault(x => x.id == promotionID);
            return View(promotion);
        }

        [HttpPost]
        public ActionResult DeletePromotion(string id , PromotionModel promotion)
        {
            try
            {
                var filter = Builders<PromotionModel>.Filter.Eq("_id", ObjectId.Parse(id));
                promotionCollection.DeleteOne(filter);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public float GetProductPrice(string id)
        {
            var productID = new ObjectId(id);
            var promotions = promotionCollection.AsQueryable<PromotionModel>().ToList();

            foreach (var item in promotions)
            {
                foreach (var product in item.products)
                {
                    if(product.Id == productID)
                    {
                        float precoAtual = product.GetPrice(false);
                        float desconto = precoAtual * (item.discountAmount/100f);
                        float newPrice = precoAtual - desconto;
                        return newPrice;
                    }
                }
            }

            return 0;
        }
    }
}

PIDI/Views/Promotion/CreatePromotion.cshtml
@model PIDI.Models.Admin.PromotionModel

@{
    ViewBag.Title = "CreatePromotion";
    var produtos = PIDI.Controllers.Admin.ProductController.Instance.GetProducts(10);
}
<div class="container">
    <h2>Cadastrar promoção</h2>

    <link type="text/css" rel="stylesheet" href="~/Scripts/pytesNET-tail.select-d6454ba/css/bootstrap4/tail.select-default.min.css" />
    <script type="text/javascript" src="~/Scripts/pytesNET-tail.select-d6454ba/js/tail.select.min.js"></script>



    @using (Html.BeginForm("CreatePromotion", "Promotion", FormMethod.Post, new { onsubmit = "return validate()", id = "promotionForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.PromotionName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PromotionName, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.PromotionName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.discountAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.discountAmount, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.discountAmount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.InitDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.InitDate, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.InitDate, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group text-monospace h4 font-weight-bold">
                <label class="control-label col-md-2" for="Produtos">Produtos</label>
                <div class="col-md-10">
                    <select class="select-move" multiple>
                        <optgroup label="Produtos">

                            @{
                                foreach (var item in produtos)
                                {
                                    <option value=@item.Id>@item.ProductName</option>
                                }
                            }
                        </optgroup>
                    </select>

                    <div class="tail-move-container"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" onclick="return validate()" value="Cadastrar   " class="btn btn-info btn-lg" />&nbsp &nbsp
                    @Html.ActionLink("Retornar", "Index", null, new { @class = "btn btn-info btn-lg"})
                </div>
            </div>
        </div>
    }
</div>
<!-- Adicionando JQuery -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>

<script type="text/javascript">

    validate = function () {
        var SelectField = tail.select(".select-move");
        var files = SelectField.options.selected;

        var myform = document.getElementById('promotionForm');
        var data = new FormData(myform);
        var array = [];

        for (var x = 0; x < files.length; x++) {
            array[x] = files[x].value;
        }
        data.append('productsString', array);
        $.ajax({
            type: "POST",
            url: '/Promotion/CreatePromotion',
            contentType: false,
            processData: false,
            data: data,
            success: function (result) {
                console.log("FOOOOOOOOOOOI");
                window.location = '/Promotion/Index'
            },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                console.log(err);
            }
        });

        return false;
    }


    tail.select(".select-move", {
        search: true,
        descriptions: true,
        hideSelected: true,
        hideDisabled: true,
        locale: "pt_BR",
        multiShowCount: false,
        stayOpen: false,
        placeholder: "Selecione os produtos",
        multiContainer: ".tail-move-container"
    });
</script>

PIDI/Views/Promotion/DeletePromotion.cshtml
@model PIDI.Models.Admin.PromotionModel

@{
    ViewBag.Title = "DeletePromotion";
}

<div class="container">
    <h2>Excluir promoção</h2>
    &nbsp
    <h3>Tem certeza que deseja excluir essa promoção?</h3>
    <di>
        <hr />
        <div class="row">
            <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                @Html.DisplayNameFor(model => model.PromotionName)
            </div>
            <div class="col-lg-10 border-bottom text-monospace h4">
                @Html.DisplayFor(model => model.PromotionName)
            </div>
            <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                @Html.DisplayNameFor(model => model.discountAmount)
            </div>
            <div class="col-lg-10 border-bottom text-monospace h4">
                @Html.DisplayFor(model => model.discountAmount)
            </div>
            <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                @Html.DisplayNameFor(model => model.InitDate)
            </div>
            <div class="col-lg-10 border-bottom text-monospace h4">
                @Html.DisplayFor(model => model.InitDate)
            </div>
            <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                @Html.DisplayNameFor(model => model.EndDate)
            </div>
            <div class="col-lg-10 border-bottom text-monospace h4">
                @Html.DisplayFor(model => model.EndDate)
            </div>
            &nbsp
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    @Html.ActionLink("Retornar", "Index", null, new { @class = "btn btn-info btn-lg" })&nbsp &nbsp &nbsp
                    <input type="submit" value="Excluir" class="btn btn-info btn-lg" />
                </div>
            }
        </div>
</div>

PIDI/Views/Promotion/EditPromotion.cshtml
@model PIDI.Models.Admin.PromotionModel

@{
    ViewBag.Title = "EditPromotion";
}

<div class="container">
    <h2>Editar promoção</h2>

    <link type="text/css" rel="stylesheet" href="~/Scripts/pytesNET-tail.select-d6454ba/css/bootstrap4/tail.select-default.min.css" />
    <script type="text/javascript" src="~/Scripts/pytesNET-tail.select-d6454ba/js/tail.select.min.js"></script>

    @using (Html.BeginForm("EditPromotion", "Promotion", FormMethod.Post, new { onsubmit = "return validate()", id = "promotionForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.PromotionName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PromotionName, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.PromotionName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.discountAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.discountAmount, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.discountAmount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.InitDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.InitDate, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.InitDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-monospace h4 font-weight-bold">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-monospace h4 font-weight-bold">
                <label class="control-label col-md-2" for="Produtos">Produtos</label>
                <div class="col-md-10">
                    <select class="select-move" multiple>
                        <optgroup label="Produtos">

                            @{
                                var filterdList = PIDI.Controllers.Admin.ProductController.Instance.GetProducts(Model.products);
                                foreach (var item in filterdList)
                                {
                                    <option value=@item.Id>@item.ProductName</option>
                                }
                            }
                        </optgroup>
                    </select>

                    <div class="tail-move-container">
                    </div>
                </div>
            </div>
            <div class="form-group text-monospace h4 font-weight-bold">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Retornar", "Index", null, new { @class = "btn btn-info btn-lg" })&nbsp
                    <input type="submit" value="Salvar" class="btn btn-info btn-lg" />
                </div>
            </div>
        </div>
    }
</div>



<!-- Adicionando JQuery -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>

<script type="text/javascript">

     $(document).ready(function () {

            var SelectField = tail.select(".select-move");

            var myIdArray = [];
            var myProductNameArray = [];

            @foreach (var d in Model.products)
            {
                @:myIdArray.push("@d.Id");
                @:myProductNameArray.push("@d.ProductName");
            }

            for (var i = 0; i < myIdArray.length; i++) {

                SelectField.options.add({
                    item: {
                        key: myIdArray[i],
                        value: myProductNameArray[i],
                        group: "#",
                        selected: true,
                        disabled: false,
                        description: ""
                    }
                });
            }
    });

    validate = function () {
        var SelectField = tail.select(".select-move");
        var files = SelectField.options.selected;

        var myform = document.getElementById('promotionForm');
        var data = new FormData(myform);
        var array = [];

        for (var x = 0; x < files.length; x++) {
            array[x] = files[x].value;
        }
        data.append('productsString', array);
        $.ajax({
            type: "POST",
            url: '/Promotion/EditPromotion?id=@Model.id',
            contentType: false,
            processData: false,
            data: data,
            success: function (result) {
                console.log("FOOOOOOOOOOOI");
                window.location = '/Promotion/Index'
            },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                console.log(err);
            }
        });

        return false;
    }

    tail.select(".select-move", {
        search: true,
        descriptions: true,
        hideSelected: true,
        hideDisabled: true,
        locale: "pt_BR",
        multiShowCount: false,
        stayOpen: false,
        placeholder: "Selecione os produtos",
        multiContainer: ".tail-move-container"
    });



</script>

PIDI/Views/Promotion/Index.cshtml
@model IEnumerable<PIDI.Models.Admin.PromotionModel>

@{
    ViewBag.Title = "Index";
}
<div class=" container-fluid">
    &nbsp
    <div class="row">
        <div class="col-md-12">
            @Html.ActionLink("Incluir promoção", "CreatePromotion", null, new { @class = "btn btn-info btn-lg" })
        </div>
    </div>

    <table class="table table-striped h4" ; style="text-align: center">
        <thead>
            <tr>
                <th class="text-monospace h3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.PromotionName)
                </th>
                <th class="text-monospace h3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.discountAmount)
                </th>
                <th class="text-monospace h3 font-weight-bold">
                    ID Produto
                </th>

                <th class="text-monospace h3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.products)
                </th>
                <th class="text-monospace h3 font-weight-bold">
                    Categoria Produto
                </th>

                <th class="text-monospace h3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.InitDate)
                </th>
                <th class="text-monospace h3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PromotionName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.discountAmount)
                    </td>


                    <td>

                        @{
                            var produtos = item.products;

                            for (int i = 0; i < produtos.Count; i++)
                            {
                                <p> @produtos[i].Id.ToString()</p>

                                if (i == 2)
                                {
                                    <p>...</p>
                                    break;
                                }
                            }

                        }
                    </td>

                    <td>

                        @{
                            for (int i = 0; i < produtos.Count; i++)
                            {
                                <p> @produtos[i].ProductName</p>

                                if (i == 2)
                                {
                                    <p>...</p>
                                    break;
                                }
                            }

                        }
                    </td>

                    <td>

                        @{
                            for (int i = 0; i < produtos.Count; i++)
                            {
                                <p> @produtos[i].Category</p>

                                if (i == 2)
                                {
                                    <p>...</p>
                                    break;
                                }
                            }
                        }
                    </td>


                    <td>
                        @Html.DisplayFor(modelItem => item.InitDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "EditPromotion", new { id = item.id }, new { @class = "btn btn-info btn-lg " })
                        @Html.ActionLink("Detalhes", "PromotionDetails", new { id = item.id }, new { @class = "btn btn-info btn-lg " })
                        @Html.ActionLink("Deletar", "DeletePromotion", new { id = item.id }, new { @class = "btn btn-info btn-lg " })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PIDI/Views/Promotion/PromotionDetails.cshtml
@model PIDI.Models.Admin.PromotionModel

@{
    ViewBag.Title = "PromotionDetails";
}
    <div class="container">
        <h2>Detalhes da promoção</h2>
        <div>
            <hr />
            <div class="row">
                <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                    @Html.DisplayNameFor(model => model.PromotionName)
                </div>
                <div class="col-lg-10 border-bottom text-monospace h4">
                    @Html.DisplayFor(model => model.PromotionName)
                </div>
                <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                    @Html.DisplayNameFor(model => model.discountAmount)
                </div>
                <div class="col-lg-10 border-bottom text-monospace h4">
                    @Html.DisplayFor(model => model.discountAmount)
                </div>
                <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                    @Html.DisplayNameFor(model => model.InitDate)
                </div>
                <div class="col-lg-10 border-bottom text-monospace h4">
                    @Html.DisplayFor(model => model.InitDate)
                </div>
                <div class="col-lg-2 border-bottom  text-monospace h4 font-weight-bold">
                    @Html.DisplayNameFor(model => model.EndDate)
                </div>
                <div class="col-lg-10 border-bottom text-monospace h4">
                    @Html.DisplayFor(model => model.EndDate)
                </div>
            </div>
        </div>&nbsp
        <p>
            @Html.ActionLink("Editar", "EditPromotion", new { id = Model.id }, new { @class = "btn btn-info btn-lg " }) &nbsp &nbsp
            @Html.ActionLink("Retornar", "Index", null, new { @class = "btn btn-info btn-lg" })
        </p>
    </div>