PIDI/Controllers/Admin/RelatorioController.cs
using MongoDB.Driver;
using System.Web.Script.Serialization;
using OfficeOpenXml;
using PIDI.App_Start;
using PIDI.Models;
using PIDI.Models.Commom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace PIDI.Controllers.Admin
{
    [Authorize(Roles = "Administrador")]
    public class RelatorioController : Controller
    {

        public static RelatorioController Instance
        {
            get
            {
                return GetInstace();
            }
            set { }
        }
        private static RelatorioController _instance;

        private MongoDBContext dBContext;
        public static List<PedidosModel> lastOrderRequest = new List<PedidosModel>();
        public static List<UserModel> lastUserRequest = new List<UserModel>();
        private static RelatorioController GetInstace()
        {
            if (_instance == null)
            {
                _instance = new RelatorioController();
                return _instance;
            }
            else
                return _instance;
        }

        #region Collections Reference

        private IMongoCollection<ProductModel> productCollection;
        private IMongoCollection<PedidosModel> orderCollection;
        private IMongoCollection<UserModel> userCollection;

        #endregion

        public RelatorioController()
        {
            dBContext = new MongoDBContext();

            productCollection = dBContext.database.GetCollection<ProductModel>("product");
            orderCollection = dBContext.database.GetCollection<PedidosModel>("orders");
            userCollection = dBContext.database.GetCollection<UserModel>("users");

        }

        #region Relatorio Pedido
        /// <summary>
        /// Gerar relatório de pedidos
        /// </summary>
        /// <returns></returns>
        public ActionResult GerarRelatorioPedido(DateTime dtInicio, DateTime dtFinal)
        {
            var pedidos = orderCollection.AsQueryable().ToList();
            var filtered = pedidos.FindAll(x => x.OrderDate.Date <= dtFinal && x.OrderDate.Date >= dtInicio);
            lastOrderRequest = filtered;

            ViewBag.dtInicio = dtInicio.ToString("dd/MM/yyyy");
            ViewBag.dtFinal = dtFinal.ToString("dd/MM/yyyy");

            return View(filtered);
        }

        [HttpPost]
        public ActionResult GerarRelatorioPedido(DateTime dtInicio, DateTime dtFinal, string orderState)
        {
            var pedidos = orderCollection.AsQueryable().ToList();
            var filtered = pedidos.FindAll(x => x.OrderDate.Date <= dtFinal && x.OrderDate.Date >= dtInicio && x.orderState == orderState);
            lastOrderRequest = filtered;

            ViewBag.dtInicio = dtInicio.ToString("dd/MM/yyyy");
            ViewBag.dtFinal = dtFinal.ToString("dd/MM/yyyy");

            return View(filtered);
        }

        public void DownloadPedidosExcel(string horaGerado)
        {
            var collection = lastOrderRequest;//db.GetCollection<EmployeeDetails>("EmployeeDetails").Find(new BsonDocument()).ToList();

            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");

            Sheet.Cells["A1"].Value = "Dia Geração Relatório";
            Sheet.Cells["B1"].Value = "Order ID";
            Sheet.Cells["C1"].Value = "Requested Products";
            Sheet.Cells["D1"].Value = "Order State";
            Sheet.Cells["E1"].Value = "Total";

            int row = 2;
            Sheet.Cells[string.Format("A{0}", row)].Value = horaGerado;

            foreach (var item in collection)
            {
                Sheet.Cells[string.Format("B{0}", row)].Value = item.OrderId;

                string produtos = "";
                for (int i = 0; i < item.produtosRequisitados.Count; i++)
                {
                    produtos += item.produtosRequisitados[i].produtoRequisitado.ProductName;
                    produtos += " x " + item.produtosRequisitados[i].Quantity + " \n ";
                }

                Sheet.Cells[string.Format("C{0}", row)].Style.WrapText = true;
                Sheet.Cells[string.Format("C{0}", row)].Value = produtos;
                Sheet.Cells[string.Format("D{0}", row)].Value = item.orderState;
                Sheet.Cells[string.Format("E{0}", row)].Value = item.Total;
                row++;
            }


            Sheet.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "RelatorioPedido.xlsx");
            Response.BinaryWrite(Ep.GetAsByteArray());
            Response.End();
        }
        #endregion

        #region Relatório Clientes
        /// <summary>
        /// Gerar relatório de pedidos
        /// </summary>
        /// <returns></returns>
        public ActionResult GerarRelatorioCliente(DateTime dtInicio, DateTime dtFinal)
        {
            var pedidos = userCollection.AsQueryable().ToList();
            var filtered = pedidos.FindAll(x => x.dtCriacao.Date <= dtFinal && x.dtCriacao.Date >= dtInicio);
            lastUserRequest = filtered;

            ViewBag.dtInicio = dtInicio.ToString("dd/MM/yyyy");
            ViewBag.dtFinal = dtFinal.ToString("dd/MM/yyyy");

            return View(filtered);
        }

        [HttpPost]
        public ActionResult GerarRelatorioCliente(DateTime dtInicio, DateTime dtFinal, string clientState)
        {
            var clientes = userCollection.AsQueryable().ToList();
            var filtered = clientes.FindAll(x => x.dtCriacao.Date <= dtFinal.Date && x.dtCriacao.Date >= dtInicio.Date);
            lastUserRequest = filtered;
            
            ViewBag.dtInicio = dtInicio.ToString("dd/MM/yyyy");
            ViewBag.dtFinal = dtFinal.ToString("dd/MM/yyyy");

            return View(filtered);
        }

        public void DownloadClienteExcel(string horaGerado)
        {
            var collection = lastUserRequest;//db.GetCollection<EmployeeDetails>("EmployeeDetails").Find(new BsonDocument()).ToList();

            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");

            Sheet.Cells["A1"].Value = "Dia Geração Relatório";
            Sheet.Cells["B1"].Value = "User ID";
            Sheet.Cells["C1"].Value = "Nome";
            Sheet.Cells["D1"].Value = "Sexo";
            Sheet.Cells["E1"].Value = "Email";
            Sheet.Cells["F1"].Value = "Data Criação";
            Sheet.Cells["G1"].Value = "Data Nascimento";

            int row = 2;
            Sheet.Cells[string.Format("A{0}", row)].Value = horaGerado;

            foreach (var item in collection)
            {
                Sheet.Cells[string.Format("B{0}", row)].Value = item.Id;
                Sheet.Cells[string.Format("C{0}", row)].Value = item.nome;
                Sheet.Cells[string.Format("D{0}", row)].Value = item.sexo;
                Sheet.Cells[string.Format("E{0}", row)].Value = item.email;
                Sheet.Cells[string.Format("F{0}", row)].Value = item.dtCriacao;
                Sheet.Cells[string.Format("G{0}", row)].Value = item.dtNascimento;
                row++;
            }


            Sheet.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename=" + "RelatorioPedido.xlsx");
            Response.BinaryWrite(Ep.GetAsByteArray());
            Response.End();
        }
        #endregion


        #region Relatório Financeiro
        /// <summary>
        /// Gerar relatório de pedidos
        /// </summary>
        /// <returns></returns>
        public ActionResult GerarRelatorioFinanceiro(DateTime dtInicio, DateTime dtFinal)
        {
            var orders = orderCollection.AsQueryable().ToList();
            var filtered = orders.FindAll(x => x.OrderDate.Date <= dtFinal && x.OrderDate.Date >= dtInicio && x.orderState == "Pago");

            List<relatorioFinanceiroElement> produtos = new List<relatorioFinanceiroElement>();

            for (int i = 0; i < filtered.Count; i++)
            {
                var order = filtered[i];
                var produtosPedido = order.produtosRequisitados;
                for (int k = 0; k < produtosPedido.Count; k++)
                {
                    var produto = produtosPedido[k];
                    bool contains = false;
                    int index = 0;

                    for (int l = 0; l < produtos.Count; l++)
                    {
                        var target = produtos[l].produto.Id;
                        if (target == produto.produtoRequisitado.Id)
                        {
                            contains = true;
                            index = l;
                            break;
                        }
                    }

                    if (!contains)
                    {
                        relatorioFinanceiroElement newProduct = new relatorioFinanceiroElement()
                        {
                            produto = produto.produtoRequisitado,
                            quantidadeVendidas = produto.Quantity,
                            dinheiroGanho = (decimal)(produto.produtoRequisitado.Preco * (float)produto.Quantity)
                        };

                        var containKey = newProduct.diasVendas.ContainsKey(order.OrderDate.Date);

                        if (containKey)
                            newProduct.diasVendas[order.OrderDate.Date] += produto.Quantity;
                        else
                            newProduct.diasVendas.Add(order.OrderDate.Date, produto.Quantity);

PIDI/Views/Relatorio/DetalhesRelatorio.cshtml
@model Dictionary<DateTime, int>
@{
    ViewBag.Title = "DetalhesRelatorio";
}

<h2>DetalhesRelatorio</h2>
<script src="~/Scripts/CanvasJSChart/canvasjs.min.js"></script>

<div id="chartContainer"></div>

<script type="text/javascript">
    window.onload = function () {
			var chart = new CanvasJS.Chart("chartContainer", {
				theme: "light2",
				animationEnabled: true,
				title: {
					text: "Dias de venda"
				},
				subtitles: [
					{ text: "Produto" }
				],
				data: [
                    {
                        type: "column", //change type to bar, line, area, pie, etc
                                        //Uncomment below line to add data coming from the controller.
					dataPoints: @Html.Raw(ViewBag.DataPoints),
				}
				]
			});
			chart.render();
		};
</script>

PIDI/Views/Relatorio/GerarRelatorioCliente.cshtml
@model IEnumerable<PIDI.Models.UserModel>

@{
    ViewBag.Title = "GerarRelatorioCliente";
    DateTime horaGerado = DateTime.Now;
}

<h2>Relatórios Clientes </h2>

<style>
    .fieldName {
        width: 120px;
        height: 25px;
        margin-left: 10px;
    }
</style>

<form action="/Relatorio/GerarRelatorioCliente" method="post">
    <div class="form-group text-monospace h4 font-weight-bold">
        <div class="input-group">

            <label class="fieldName" for="dtNascimento">Data de Inicio</label>
            <input class="form-control form-control-lg text-box single-line" id="dtInicio" name="dtInicio" required="required" type="date" value="">
            <span class="field-validation-valid text-danger" data-valmsg-for="dtInicio" data-valmsg-replace="true"></span>

            <label class="fieldName" for="dtNascimento">Data Final</label>
            <input class="form-control form-control-lg text-box single-line" id="dtFinal" name="dtFinal" required="required" type="date" value="">
            <span class="field-validation-valid text-danger" data-valmsg-for="dtFinal" data-valmsg-replace="true"></span>


            &nbsp &nbsp
            <input class="btn btn-info btn-lg" type="submit" value="Gerar relatório">
        </div>

    </div>
</form>

<table class="table table-striped h4" ; style="text-align: center">
    <thead>
        <tr>
            <th>
                Dia Geração relatório : @horaGerado | Periodo Analisado @ViewBag.dtInicio - @ViewBag.dtFinal
            <td>
                @{
                    @Html.ActionLink("Export Excel", "DownloadClienteExcel", "Relatorio", new { horaGerado = horaGerado.ToString()}, new { @class = "btn btn-info btn-lg " });
                }
            </td>
            </th>
        </tr>
    </thead>
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.userId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dtCriacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dtNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpf)
            </th>

            <th></th>
        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @*@Html.DisplayFor(modelItem => item.userId)*@
                    @item.Id.ToString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.sobrenome)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.dtCriacao)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.dtNascimento)
                </td>

                <td>
                   @Html.DisplayFor(modelItem => item.cpf)
                </td>
            </tr>
        }
    </tbody>
</table>

PIDI/Views/Relatorio/GerarRelatorioFinanceiro.cshtml
@model IEnumerable<PIDI.Controllers.Admin.relatorioFinanceiroElement>

@{
    ViewBag.Title = "GerarRelatorioFinanceiro";
    DateTime horaGerado = DateTime.Now;

}&nbsp &nbsp

<div class="container-fluid">

    <h2>Relatórios Financeiro </h2>&nbsp &nbsp

    <style>
        .fieldName {
            width: 120px;
            height: 30px;
            margin-left: 10px;
            text-align: center;
        }
    </style>

    <form action="/Relatorio/GerarRelatorioFinanceiro" method="post">
        <div class="form-group text-monospace h4 font-weight-bold">
            <div class="input-group">

                <label class="fieldName" for="dtNascimento">Data Início</label>
                <input class="form-control form-control-lg text-box single-line" id="dtInicio" name="dtInicio" required="required" type="date" value="">
                <span class="field-validation-valid text-danger" data-valmsg-for="dtInicio" data-valmsg-replace="true"></span>

                <label class="fieldName" for="dtNascimento">Data Final</label>
                <input class="form-control form-control-lg text-box single-line" id="dtFinal" name="dtFinal" required="required" type="date" value="">
                <span class="field-validation-valid text-danger" data-valmsg-for="dtFinal" data-valmsg-replace="true"></span>

                &nbsp &nbsp
                <input class="btn btn-info btn-lg" type="submit" value="Gerar relatório">
            </div>

        </div>
    </form>
    <table class="table table-striped h4" ; style="text-align: center">
        <thead>
            <tr>
                <th>
                    Dia Geração relatório : @horaGerado | Periodo Analisado @ViewBag.dtInicio - @ViewBag.dtFinal
                <td>
                    @Html.ActionLink("Exportar para Excel", "DownloadPedidosExcel", "Relatorio", new { horaGerado = horaGerado.ToString( )}, new { @class = "btn btn-info btn-lg " })
                </td>
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    Id Produto
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.produto.ProductName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.quantidadeVendidas)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dinheiroGanho)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.produto.Id.ToString()
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.produto.ProductName)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.quantidadeVendidas)
                    </td>

                    <td>
                       R$ @Html.DisplayFor(modelItem => item.dinheiroGanho)
                    </td>
                    <td>
                        @Html.ActionLink("Detalhes", "DetalhesRelatorio", new { vendas = PIDI.Controllers.Admin.RelatorioController.Instance.DictionaryToString(item.diasVendas) }, new { @class = "btn btn-info btn-lg " })
                    </td>

                </tr>
            }
        </tbody>
    </table>
    
</div>

PIDI/Views/Relatorio/GerarRelatorioPedido.cshtml
@model IEnumerable<PIDI.Models.Commom.PedidosModel>

@{
    ViewBag.Title = "GerarRelatorioPedido";
    DateTime horaGerado = DateTime.Now;
}&nbsp &nbsp

<div class="container-fluid">

    <h2>Relatórios Pedidos </h2>&nbsp &nbsp

    <style>
        .fieldName {
            width: 120px;
            height: 30px;
            margin-left: 10px;
            text-align: center;
        }
    </style>

    <form action="/Relatorio/GerarRelatorioPedido" method="post">
        <div class="form-group text-monospace h4 font-weight-bold">
            <div class="input-group">

                <label class="fieldName" for="dtNascimento">Data Início</label>
                <input class="form-control form-control-lg text-box single-line" id="dtInicio" name="dtInicio" required="required" type="date" value="">
                <span class="field-validation-valid text-danger" data-valmsg-for="dtInicio" data-valmsg-replace="true"></span>

                <label class="fieldName" for="dtNascimento">Data Final</label>
                <input class="form-control form-control-lg text-box single-line" id="dtFinal" name="dtFinal" required="required" type="date" value="">
                <span class="field-validation-valid text-danger" data-valmsg-for="dtFinal" data-valmsg-replace="true"></span>

                <label class="fieldName" for="orderState">Status Pedido</label>
                <select class="form-control" id="orderState" name="orderState">
                    <option>Aguardando Pagamento</option>
                    <option>Pago</option>
                    <option>Cancelado</option>
                </select>
                &nbsp &nbsp
                <input class="btn btn-info btn-lg" type="submit" value="Gerar relatório">
            </div>

        </div>
    </form>
    <table class="table table-striped h4" ; style="text-align: center">
        <thead>
            <tr>
                <th>
                    Dia Geração relatório : @horaGerado | Periodo Analisado @ViewBag.dtInicio - @ViewBag.dtFinal
                <td>
                    @{
                        @Html.ActionLink("Exportar para Excel", "DownloadPedidosExcel", "Relatorio", new { horaGerado = horaGerado.ToString() }, new { @class = "btn btn-info btn-lg " });
                    }
                </td>
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OrderId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.produtosRequisitados)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.orderState)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.OrderId.ToString()
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                        @{
                            for (int i = 0; i < item.produtosRequisitados.Count; i++)
                            {
                                if (i == 3)
                                {
                                    <p>...</p>
                                    break;
                                }

                                var product = item.produtosRequisitados[i];
                                <p>@product.produtoRequisitado.ProductName x @product.Quantity</p>
                            }
                        }
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.orderState)
                    </td>

                    <td>
                        R$ @Html.DisplayFor(modelItem => item.Total)
                    </td>

                    <td>
                        @Html.ActionLink("Detalhes", "Details", "Pedido", new { area = "Pedido", id = item.OrderId }, new { @class = "btn btn-info btn-lg " })
                    </td>
                </tr>
            }
        </tbody>
    </table>
        
</div>